-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.campaign
(
    cf_id integer NOT NULL,
    contact_id integer NOT NULL,
    company_name character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default" NOT NULL,
    goal double precision NOT NULL,
    pledged double precision NOT NULL,
    outcome character(1) COLLATE pg_catalog."default" NOT NULL,
    backers_count integer NOT NULL,
    country character(2) COLLATE pg_catalog."default" NOT NULL,
    currency character(2) COLLATE pg_catalog."default" NOT NULL,
    launch_date date NOT NULL,
    end_date date NOT NULL,
    category_id character varying(4) COLLATE pg_catalog."default" NOT NULL,
    subcategory_id character varying(4) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cf_id PRIMARY KEY (cf_id)
);

CREATE TABLE IF NOT EXISTS public.category
(
    category_id character varying(4) COLLATE pg_catalog."default" NOT NULL,
    category character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id integer NOT NULL,
    first_name character varying COLLATE pg_catalog."default" NOT NULL,
    last_name character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT contacts_pkey PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public.subcategory
(
    subcategory_id character varying(8) COLLATE pg_catalog."default" NOT NULL,
    subcategory character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT subcategory_pkey PRIMARY KEY (subcategory_id)
);

ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT category_id FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT contact_id FOREIGN KEY (contact_id)
    REFERENCES public.contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT subcategory_id FOREIGN KEY (subcategory_id)
    REFERENCES public.subcategory (subcategory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;